# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Level.create(name: "Bob-omb Battlefield", category: "stage", official_course_number: 1)
Level.create(name: "Whomp's Fortress", category: "stage", official_course_number: 2)
Level.create(name: "Jolly Roger Bay", category: "stage", official_course_number: 3)
Level.create(name: "Cool, Cool Mountain", category: "stage", official_course_number: 4)
Level.create(name: "Big Boo's Haunt", category: "stage", official_course_number: 5)
Level.create(name: "Hazy Maze Cave", category: "stage", official_course_number: 6)
Level.create(name: "Lethal Lava Land", category: "stage", official_course_number: 7)
Level.create(name: "Shifting Sand Land", category: "stage", official_course_number: 8)
Level.create(name: "Dire Dire Docks", category: "stage", official_course_number: 9)
Level.create(name: "Wet Dry World", category: "stage", official_course_number: 11)
Level.create(name: "Tall, Tall Mountain", category: "stage", official_course_number: 12)
Level.create(name: "Snowman's Land", category: "stage")
Level.create(name: "Tiny Huge Island", category: "stage")
Level.create(name: "Tick Tock Clock", category: "stage")
Level.create(name: "Rainbow Ride", category: "stage")
Level.create(name: "Princess Peach's Secret Slide", category: "secret")
Level.create(name: "Aquarium", category: "secret")
Level.create(name: "Wing Cap", category: "secret")
Level.create(name: "Metal Cap", category: "secret")
Level.create(name: "Vanish Cap", category: "secret")
Level.create(name: "Wing Mario over the Rainbow", category: "secret")
Level.create(name: "Bowser in the Dark World", category: "secret")
Level.create(name: "Bowser in the Fire Sea", category: "secret")
Level.create(name: "Bowser in the Sky", category: "secret")

Star.create(name: "Big Bob-omb on the Summit", star_number: 1, level_id: 1, star_type: "boss", is_unique: true)
Star.create(name: "Footrace with Koopa the Quick", level_id: 1, star_number: 2, star_type: "spawn")
Star.create(name: "Shoot to the Island in the Sky", level_id: 1, star_number: 3, star_type: "box")
Star.create(name: "Find the 8 Red Coins", level_id: 1, star_number: 4, star_type: "reds")
Star.create(name: "Mario Wings to the Sky", level_id: 1, star_number: 5, star_type: "secrets")
Star.create(name: "Behind Chain Chomp’s Gate", level_id: 1, star_number: 6, star_type: "naked")
Star.create(name: "Bob-omb Battlefield 100 Coins", level_id: 1, star_number: 7, star_type: "100c")
Star.create(name: "Chip off Whomp’s Block", level_id: 2, star_number: 1, star_type: "boss")
Star.create(name: "To the Top of the Fortress", level_id: 2, star_number: 2, star_type: "naked")
Star.create(name: "Shoot into the Wild Blue", level_id: 2, star_number: 3, star_type: "naked")
Star.create(name: "Red Coins on the Floating Isle", level_id: 2, star_number: 4, star_type: "reds")
Star.create(name: "Fall onto the Caged Island", level_id: 2, star_number: 5, star_type: "naked")
Star.create(name: "Blast Away the Wall", level_id: 2, star_number: 6, star_type: "naked")
Star.create(name: "Whomp's Fortress 100 Coins", level_id: 2, star_number: 7, star_type: "100c")
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)
Star.create(name: "", level_id: 3, star_number:, star_type: "", is_unique: true)


Run.create(level_id: 1, minutes: 4, seconds: 48, milliseconds: 15, date_performed: 2024-11-23)
Run.create(level_id: 1, minutes: 4, seconds: 54, milliseconds: 30, date_performed: 2024-11-23)
Run.create(level_id: 1, minutes: 5, seconds: 6, milliseconds: 82, date_performed: 2024-11-26)
Run.create(level_id: 1, minutes: 4, seconds: 43, milliseconds: 18, date_performed: 2024-11-28)
Run.create(level_id: 1, minutes: 4, seconds: 52, milliseconds: 98, date_performed: 2024-12-01)
Run.create(level_id: 1, minutes: 4, seconds: 46, milliseconds: 0, date_performed: 2024-12-02)
Run.create(level_id: 1, minutes: 5, seconds: 2, milliseconds: 15, date_performed: 2024-12-24)
Run.create(level_id: 1, minutes: 5, seconds: 8, milliseconds: 73, date_performed: 2024-12-28)
Run.create(level_id: 1, minutes: 5, seconds: 29, milliseconds: 55, date_performed: 2024-12-28)
Run.create(level_id: 1, minutes: 4, seconds: 32, milliseconds: 78, date_performed: 2025-01-03)

Run.create(level_id: 2, minutes: 2, seconds: 35, milliseconds: 87, date_performed: 2024-11-23)
Run.create(level_id: 2, minutes: 2, seconds: 57, milliseconds: 87, date_performed: 2024-11-28)
Run.create(level_id: 2, minutes: 2, seconds: 43, milliseconds: 78, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 50, milliseconds: 6, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 17, milliseconds: 70, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 43, milliseconds: 8, date_performed: 2024-12-01)
Run.create(level_id: 2, minutes: 2, seconds: 18, milliseconds: 13, date_performed: 2024-12-02)
Run.create(level_id: 2, minutes: 2, seconds: 23, milliseconds: 57, date_performed: 2024-12-24)
Run.create(level_id: 2, minutes: 2, seconds: 39, milliseconds: 33, date_performed: 2024-12-26)
Run.create(level_id: 2, minutes: 2, seconds: 27, milliseconds: 2, date_performed: 2024-12-28)
Run.create(level_id: 2, minutes: 2, seconds: 37, milliseconds: 22, date_performed: 2024-12-28)

Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
Run.create(level_id: 3, minutes:, seconds:, milliseconds:, date_performed:)
