# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Level.create(name: "Bob-omb Battlefield", category: "stage", official_course_number: 1)
Level.create(name: "Whomp's Fortress", category: "stage", official_course_number: 2)
Level.create(name: "Jolly Roger Bay", category: "stage", official_course_number: 3)
Level.create(name: "Cool, Cool Mountain", category: "stage", official_course_number: 4)
Level.create(name: "Big Boo's Haunt", category: "stage", official_course_number: 5)
Level.create(name: "Hazy Maze Cave", category: "stage", official_course_number: 6)
Level.create(name: "Lethal Lava Land", category: "stage", official_course_number: 7)
Level.create(name: "Shifting Sand Land", category: "stage", official_course_number: 8)
Level.create(name: "Dire Dire Docks", category: "stage", official_course_number: 9)
Level.create(name: "Snowman's Land", category: "stage", official_course_number: 10)
Level.create(name: "Wet Dry World", category: "stage", official_course_number: 11)
Level.create(name: "Tall, Tall Mountain", category: "stage", official_course_number: 12)
Level.create(name: "Tiny Huge Island", category: "stage", official_course_number: 13)
Level.create(name: "Tick Tock Clock", category: "stage", official_course_number: 14)
Level.create(name: "Rainbow Ride", category: "stage", official_course_number: 15)
Level.create(name: "Princess Peach's Secret Slide", category: "secret", official_course_number: 16)
Level.create(name: "Aquarium", category: "secret", official_course_number: 17)
Level.create(name: "Wing Cap", category: "secret", official_course_number: 18)
Level.create(name: "Metal Cap", category: "secret", official_course_number: 19)
Level.create(name: "Vanish Cap", category: "secret", official_course_number: 20)
Level.create(name: "Bowser in the Dark World", category: "secret", official_course_number: 21)
Level.create(name: "Bowser in the Fire Sea", category: "secret", official_course_number: 22)
Level.create(name: "Bowser in the Sky", category: "secret", official_course_number: 23)
Level.create(name: "Wing Mario over the Rainbow", category: "secret", official_course_number: 24)

Star.create(name: "Big Bob-omb on the Summit", star_number: 1, level_id: 1, star_type: "boss", is_unique: true)
Star.create(name: "Footrace with Koopa the Quick", level_id: 1, star_number: 2, star_type: "spawn", is_unique: true)
Star.create(name: "Shoot to the Island in the Sky", level_id: 1, star_number: 3, star_type: "box", is_unique: true)
Star.create(name: "Find the 8 Red Coins", level_id: 1, star_number: 4, star_type: "reds", is_unique: true)
Star.create(name: "Mario Wings to the Sky", level_id: 1, star_number: 5, star_type: "secrets", is_unique: true)
Star.create(name: "Behind Chain Chomp’s Gate", level_id: 1, star_number: 6, star_type: "naked", is_unique: true)
Star.create(name: "Bob-omb Battlefield 100 Coins", level_id: 1, star_number: 7, star_type: "100c", is_unique: true)

Star.create(name: "Chip off Whomp’s Block", level_id: 2, star_number: 1, star_type: "boss", is_unique: true)
Star.create(name: "To the Top of the Fortress", level_id: 2, star_number: 2, star_type: "naked", is_unique: false)
Star.create(name: "Shoot into the Wild Blue", level_id: 2, star_number: 3, star_type: "naked", is_unique: false)
Star.create(name: "Red Coins on the Floating Isle", level_id: 2, star_number: 4, star_type: "reds", is_unique: true)
Star.create(name: "Fall onto the Caged Island", level_id: 2, star_number: 5, star_type: "naked", is_unique: false)
Star.create(name: "Blast Away the Wall", level_id: 2, star_number: 6, star_type: "naked", is_unique: false)
Star.create(name: "Whomp's Fortress 100 Coins", level_id: 2, star_number: 7, star_type: "100c", is_unique: true)

Star.create(name: "Plunder in the Sunken Ship", level_id: 3, star_number: 1, star_type: "box - alt area", is_unique: true)
Star.create(name: "Can the Eel Come out and Play?", level_id: 3, star_number: 2, star_type: "spawn", is_unique: true)
Star.create(name: "Treasure of the Ocean Cave", level_id: 3, star_number: 3, star_type: "spawn", is_unique: true)
Star.create(name: "Red Coins on the Ship Afloat", level_id: 3, star_number: 4, star_type: "reds", is_unique: true)
Star.create(name: "Blast to the Stone Pillar", level_id: 3, star_number: 5, star_type: "box", is_unique: true)
Star.create(name: "Through the Jet Stream", level_id: 3, star_number: 6, star_type: "naked", is_unique: true)
Star.create(name: "Jolly Roger Bay 100 Coins", level_id: 3, star_number: 7, star_type: "100c", is_unique: true)

Star.create(name: "Slip Slidin’ Away", level_id: 4, star_number: 1, star_type: "spawn", is_unique: true)
Star.create(name: "Li’l Penguin Lost", level_id: 4, star_number: 2, star_type: "spawn", is_unique: true)
Star.create(name: "Big Penguin Race", level_id: 4, star_number: 3, star_type: "spawn - alt area", is_unique: true)
Star.create(name: "Frosty Slide for 8 Red Coins", level_id: 4, star_number: 4, star_type: 4, is_unique: true)
Star.create(name: "Snowman’s Lost his Head", level_id: 4, star_number: 5, star_type: 5, is_unique: true)
Star.create(name: "Wall Kicks will Work", level_id: 4, star_number: 6, star_type: 6, is_unique: true)
Star.create(name: "Cool, Cool Mountain 100 Coins", level_id: 4, star_number: 7, star_type: 7, is_unique: true)

Run.create(level_id: 1, minutes: 4, seconds: 48, milliseconds: 15, date_performed: 2024-11-23)
Run.create(level_id: 1, minutes: 4, seconds: 54, milliseconds: 30, date_performed: 2024-11-23)
Run.create(level_id: 1, minutes: 5, seconds: 6, milliseconds: 82, date_performed: 2024-11-26)
Run.create(level_id: 1, minutes: 4, seconds: 43, milliseconds: 18, date_performed: 2024-11-28)
Run.create(level_id: 1, minutes: 4, seconds: 52, milliseconds: 98, date_performed: 2024-12-01)
Run.create(level_id: 1, minutes: 4, seconds: 46, milliseconds: 0, date_performed: 2024-12-02)
Run.create(level_id: 1, minutes: 5, seconds: 2, milliseconds: 15, date_performed: 2024-12-24)
Run.create(level_id: 1, minutes: 5, seconds: 8, milliseconds: 73, date_performed: 2024-12-28)
Run.create(level_id: 1, minutes: 5, seconds: 29, milliseconds: 55, date_performed: 2024-12-28)
Run.create(level_id: 1, minutes: 4, seconds: 32, milliseconds: 78, date_performed: 2025-01-03)

Run.create(level_id: 2, minutes: 2, seconds: 35, milliseconds: 87, date_performed: 2024-11-23)
Run.create(level_id: 2, minutes: 2, seconds: 57, milliseconds: 87, date_performed: 2024-11-28)
Run.create(level_id: 2, minutes: 2, seconds: 43, milliseconds: 78, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 50, milliseconds: 6, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 17, milliseconds: 70, date_performed: 2024-11-29)
Run.create(level_id: 2, minutes: 2, seconds: 43, milliseconds: 8, date_performed: 2024-12-01)
Run.create(level_id: 2, minutes: 2, seconds: 18, milliseconds: 13, date_performed: 2024-12-02)
Run.create(level_id: 2, minutes: 2, seconds: 23, milliseconds: 57, date_performed: 2024-12-24)
Run.create(level_id: 2, minutes: 2, seconds: 39, milliseconds: 33, date_performed: 2024-12-26)
Run.create(level_id: 2, minutes: 2, seconds: 27, milliseconds: 2, date_performed: 2024-12-28)
Run.create(level_id: 2, minutes: 2, seconds: 37, milliseconds: 22, date_performed: 2024-12-28)

Run.create(level_id: 3, minutes: 4, seconds: 47, milliseconds: 27, date_performed: 2024-11-20)
Run.create(level_id: 3, minutes: 4, seconds: 3, milliseconds: 52, date_performed: 2024-11-20)
Run.create(level_id: 3, minutes: 5, seconds: 15, milliseconds: 77, date_performed: 2024-11-23)
Run.create(level_id: 3, minutes: 4, seconds: 41, milliseconds: 95, date_performed: 2024-11-28)
Run.create(level_id: 3, minutes: 4, seconds: 47, milliseconds: 10, date_performed: 2024-11-29)
Run.create(level_id: 3, minutes: 6, seconds: 5, milliseconds: 47, date_performed: 2024-12-01)
Run.create(level_id: 3, minutes: 4, seconds: 32, milliseconds: 53, date_performed: 2024-12-10)
Run.create(level_id: 3, minutes: 5, seconds: 9, milliseconds: 13, date_performed: 2024-12-24)
Run.create(level_id: 3, minutes: 4, seconds: 56, milliseconds: 90, date_performed: 2024-12-28)
Run.create(level_id: 3, minutes: 4, seconds: 29, milliseconds: 73, date_performed: 2024-12-28)
